### ISSUE TITLE
Object of type 'Neo.VM.Types.Integer' cannot be converted to type 'Neo.VM.Types.Array'.

### ISSUE THREAD

**Issue by djm34** [neow3j/neow3j#434]
Hello, 

I tried to run CompileAndDeploy.java from version 3.7.0 on a private network (that network still uses neo3-preview4, so it could be the reason
I got this error:

Exception in thread "main" io.neow3j.transaction.exceptions.TransactionConfigurationException: The vm exited due to the following exception: Object of type 'Neo.VM.Types.Integer' cannot be converted to type 'Neo.VM.Types.Array'.
        at io.neow3j.contract.TransactionBuilder.getSystemFeeForScript(TransactionBuilder.java:402)
        at io.neow3j.contract.TransactionBuilder.buildTransaction(TransactionBuilder.java:312)
        at io.neow3j.contract.TransactionBuilder.sign(TransactionBuilder.java:486)
        at io.neow3j.examples.contractdev.CompileAndDeploy.main(CompileAndDeploy.java:64)

FAILURE: Build failed with an exception.

for info, the private network also attempt to reduce the amount of fee actually

Thanks for your help

**Comment by csmuller** [comment]
Hey @djm34, Can you upgrade your private network to neo3-preview5?
I tested `CompileAndDeploy` with an up to date private network and didn't get that issue. There are considerable changes that make contracts compiled for preview5 incompatible with a preview4 node.

**Comment by csmuller** [comment]
Can you tell us what environment you are using for development, i.e., which OS, IDE or editor? It's helpful for us to know how users of neow3j work.

About the private network. I don't know what you are currently using, but I recommend using [neo-express](https://github.com/neo-project/neo-express). The latest release that is preview5 compatible can be found [here](https://github.com/neo-project/neo-express/releases/tag/2.0.9-preview). You will need the `dotnet` command line tool installed locally.

**Comment by djm34** [comment]
Hi, 
ok I will update to neo3-preview5. 
regarding my work environnement, I am currently using visual studio code remote session from my pc. neow3j is running on a linux machine using ubuntu 20.04.

**Comment by csmuller** [comment]
I assume the problem got resolved when updating to neo3-preview5. Feel free to reopen this issue if that is not true.
