### ISSUE TITLE
Magic should be long.

### ISSUE THREAD

**Issue by hurui200320** [neow3j/neow3j#560]
When neo-express generate a magic bigger than int, neow3j will throw an Exception:

```
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Numeric value (4232068425) out of range of int
 at [Source: (okio.RealBufferedSource$1); line: 1, column: 125] (through reference chain: io.neow3j.protocol.core.response.NeoGetVersion["result"]->io.neow3j.protocol.core.response.NeoGetVersion$Result["network"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:127)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at io.neow3j.protocol.Neow3j.getNetworkMagicNumber(Neow3j.java:63)
        at io.neow3j.transaction.Transaction.getHashData(Transaction.java:315)
        at io.neow3j.transaction.TransactionBuilder.sign(TransactionBuilder.java:470)
        at info.skyblond.nekohit.example.ContractExample.createWCA(ContractExample.java:38)
        at info.skyblond.nekohit.example.ContractExample.main(ContractExample.java:17)
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (4232068425) out of range of int
 at [Source: (okio.RealBufferedSource$1); line: 1, column: 135]
```

And the value `4232068425` is exactly the private net magic in neo-express config file:
```
{
  "magic": 4232068425,
  "address-version": 53,
  "consensus-nodes": [
    {
      "tcp-port": 50013,
      "ws-port": 50014,
      "rpc-port": 50012,
      "wallet": {
        "name": "node1",
 // ......
```

Looks like neow3j trying to parse magic number into int value, which should be long value.

**Comment by csmuller** [comment]
Fixed in #563. Fix will be available in next release.
