### ISSUE TITLE
ContractParameter.hash160 issues

### ISSUE THREAD

**Issue by ykoitzsch** [neow3j/neow3j#562]
I am trying to pass  some params when calling a contract but as soon as I use ContractParameter.hash160 it throws an exception.
```
NeoSendRawTransaction response = neoToken
                .transferFromSpecificAccounts(
                        WALLET,
                        targetAddress,
                        new BigInteger("2"),
                        ContractParameter.array(
                            ContractParameter.string("lkjsdf83u4lknldf93"),
                            ContractParameter.integer(3),
                            ContractParameter.array(
                                ContractParameter.hash160(GasToken.SCRIPT_HASH),
                                ContractParameter.hash160(NeoToken.SCRIPT_HASH)
                            )
                        ),
                        ALICE.getScriptHash()
                ).signers(Signer.calledByEntry(ALICE.getScriptHash()))
                .sign() 
                .send();
        trackSentTransaction(response);
```

Exception:

```
Exception in thread "main" io.neow3j.transaction.exceptions.TransactionConfigurationException: The vm exited due to the following exception: Unable to translate bytes [CF] at index 0 from specified code page to Unicode.
        at io.neow3j.transaction.TransactionBuilder.getSystemFeeForScript(TransactionBuilder.java:397)
        at io.neow3j.transaction.TransactionBuilder.buildTransaction(TransactionBuilder.java:309)
        at io.neow3j.transaction.TransactionBuilder.sign(TransactionBuilder.java:469)
```

**Comment by csmuller** [comment]
So, does that mean that it works if you use, e.g., `ContractParameter.byteArray` instead of `hash160`?

**Comment by csmuller** [comment]
@ykoitzsch, I assume that your transfer is directed to a contract, which will process the 'data'  in its `onPayment` function. And the invocation probably fails somewhere in that function call.

Doing this transfer to a normal account, with the data array you provided, does not lead to an error in my tests.

**Comment by csmuller** [comment]
@ykoitzsch Is this problem still persisting or can i close the issue?

**Comment by gsmachado** [comment]
Hey @ykoitzsch, we're closing this issue for now. If you still have problems, or has anything to add, let us know! 😄
