### ISSUE TITLE
CipherException when creating BIP39 wallet and creating a wallet file with a newly created account

### ISSUE THREAD

**Issue by cloud8little** [neow3j/neow3j#6]
Version: 1.0.6

Exception in thread "main" io.neow3j.crypto.exceptions.CipherException: Error performing cipher operation
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:172)
	at io.neow3j.crypto.Wallet.encrypt(Wallet.java:124)
	at io.neow3j.crypto.Wallet.createAccount(Wallet.java:59)
	at io.neow3j.crypto.Wallet.createStandardAccount(Wallet.java:75)
	at io.neow3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:53)
	at io.neow3j.crypto.WalletUtils.generateBip39Wallet(WalletUtils.java:93)
	at Main.main(Main.java:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:167)
	... 11 more

`        Path tempDirectory = Files.createTempDirectory("wallet-dir-prefix-test", new FileAttribute[0]);
        Bip39Wallet bip39Wallet = WalletUtils.generateBip39Wallet("myPassw0rd!@#", tempDirectory.toFile());
        String mnemonicWords = bip39Wallet.getMnemonic();
        System.out.println("mnemonic words: " + mnemonicWords);`

Generate New Wallet File:

`   Path tempDirectory = Files.createTempDirectory("wallet-dir-prefix-test", new FileAttribute[0]);
        String fileName = WalletUtils.generateNewWalletFile("myPassw0rd!@#", tempDirectory.toFile());
        System.out.println("Wallet file path: " + Paths.get(tempDirectory.toString(), new String[]{fileName}));`

Error Message:

`Exception in thread "main" io.neow3j.crypto.exceptions.CipherException: Error performing cipher operation
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:172)
	at io.neow3j.crypto.Wallet.encrypt(Wallet.java:124)
	at io.neow3j.crypto.Wallet.createAccount(Wallet.java:59)
	at io.neow3j.crypto.Wallet.createStandardAccount(Wallet.java:75)
	at io.neow3j.crypto.WalletUtils.generateWalletFile(WalletUtils.java:53)
	at io.neow3j.crypto.WalletUtils.generateNewWalletFile(WalletUtils.java:45)
	at Main.main(Main.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:167)
	... 11 more`

**Comment by gsmachado** [comment]
@cloud8little: I modified a bit how I register the BouncyCastle provider. I released a possible fix on `1.0.7`. Please, re-test it.

If you experience that the issue was not yet fixed, please re-open it.

**Comment by cloud8little** [comment]
The issue still exists with 1.0.7.

**Comment by cloud8little** [comment]
It turns out to be the problem of the jurisdiction (China), solution(remove the key size restriction): https://www.andreafortuna.org/programming/java-tips-how-to-fix-the-invalidkeyexception-illegal-key-size-or-default-parameters-runtime/
