### ISSUE TITLE
CipherException when creating a password-protected account (NEP-2) based on a key pair

### ISSUE THREAD

**Issue by cloud8little** [neow3j/neow3j#8]
`        WalletFile wallet = Wallet.createStandardWallet();
        ECKeyPair ecKeyPair1 = Keys.createEcKeyPair();
        WalletFile.Account account = Wallet.createStandardAccount("myPassw0rd!@#", ecKeyPair1);`

Exception in thread "main" io.neow3j.crypto.exceptions.CipherException: Error performing cipher operation
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:172)
	at io.neow3j.crypto.Wallet.encrypt(Wallet.java:124)
	at io.neow3j.crypto.Wallet.createAccount(Wallet.java:59)
	at io.neow3j.crypto.Wallet.createStandardAccount(Wallet.java:75)
	at Main.main(Main.java:145)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
	at javax.crypto.Cipher.implInit(Cipher.java:801)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1249)
	at javax.crypto.Cipher.init(Cipher.java:1186)
	at io.neow3j.crypto.Wallet.performCipherOperation(Wallet.java:167)
	... 9 more

**Comment by gsmachado** [comment]
@cloud8little: I modified a bit how I register the BouncyCastle provider (see #6). I released a possible fix on 1.0.7. Please, re-test it.

If you experience that the issue was not yet fixed, please re-open it.

**Comment by gsmachado** [comment]
@cloud8little thanks for the feedback.

So, can you please provide me:
1) Your Java version (paste me the result of `java -version` command, on a terminal)
2) Your OS version (Mac, Windows, Linux, and also which version, specifically)

Once I get this, I will be able to try to reproduce the issue and better investigate it.

**Comment by cloud8little** [comment]
java version "1.8.0_192" 
OS version: win10 Enterprise 

> @cloud8little: I modified a bit how I register the BouncyCastle provider (see #6). I released a possible fix on 1.0.7. Please, re-test it.
> 
> If you experience that the issue was not yet fixed, please re-open it.

**Comment by cloud8little** [comment]
It turns out to be the problem of the jurisdiction (China), solution(remove the key size restriction): https://www.andreafortuna.org/programming/java-tips-how-to-fix-the-invalidkeyexception-illegal-key-size-or-default-parameters-runtime/, @gsmachado this issue can be closed now.
