### ISSUE TITLE
NeoFS SDK: treat unexpected errors coming from shared lib

### ISSUE THREAD

**Issue by gsmachado** [neow3j/neow3j#892]
Example:

```
Exception in thread "main" java.lang.IllegalArgumentException: There exists no supported response type with the provided string value. The provided string value was *fmt.wrapError.
	at io.neow3j.neofs.lib.responses.ResponseType.fromString(ResponseType.java:32)
	at io.neow3j.neofs.lib.responses.Response.getType(Response.java:10)
	at io.neow3j.neofs.lib.responses.Response.isType(Response.java:14)
	at io.neow3j.neofs.sdk.NeoFSClient.throwIfUnexpectedResponseType(NeoFSClient.java:252)
	at io.neow3j.neofs.sdk.NeoFSClient.getBalance(NeoFSClient.java:106)
	at test.neofs.App.main(App.java:22)
```

Meaning that `*fmt.wrapError` should be converted to an error type in Java.

Concrete use case: trying to connect to a NeoFS node host that doesn't exist (not available).

**Comment by mialbu** [comment]
I've looked a bit into this, and I don't think this issue can be taken until development for NeoFS in the shared-lib is continued.
The problem with it is that the shared-lib currently returns the exact type of the error in Golang. This can also include a type `*fmt.wrapError` as in the example provided above. However, I think in case of an error the shared-lib should provide a well-defined error type, so that there's just a comparison needed in neow3j. If the unknown error type is just passed on from the shared-lib, neow3j will have to do some checks whether the type is `fmt.Error` or `fmt.wrapError`, etc. which should be avoided.

I've opened an issue in the shared-lib for this: https://github.com/AxLabs/neofs-shared-lib/issues/25

fyi, @gsmachado
